<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net48</TargetFramework>
        <Version>2.7.0.0</Version>
        <Title>sqlcon</Title>
        <Description>Sql Server Console</Description>
        <Configuration>datconn</Configuration>
        <Company>Datum Connect</Company>
        <Product>sqlcon</Product>
        <Copyright>Copyright ©  DATCONN 2012-2024</Copyright>
        <Trademark>datconn</Trademark>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Windows\images\AlignHorizontalTop_16x16.png" />
      <None Remove="Windows\images\Close_16x16.png" />
      <None Remove="Windows\images\database.png" />
      <None Remove="Windows\images\Home_16x16.png" />
      <None Remove="Windows\images\key.png" />
      <None Remove="Windows\images\New_16x16.png" />
      <None Remove="Windows\images\Next_16x16.png" />
      <None Remove="Windows\images\Open_16x16.png" />
      <None Remove="Windows\images\Save_16x16.png" />
      <None Remove="Windows\images\SelectTable_16x16.png" />
      <None Remove="Windows\images\server.png" />
      <None Remove="Windows\images\server_error.png" />
      <None Remove="Windows\images\Table_16x16.png" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Tie" Version="2.0.11" />
        <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\syscore\syscore.csproj" />
        <ProjectReference Include="..\SysData.Sqlite\SysData.Sqlite.csproj" />
        <ProjectReference Include="..\SysData.SqlServerCe\SysData.SqlServerCe.csproj" />
    </ItemGroup>
    <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
        <Reference Include="PresentationCore" />
        <Reference Include="PresentationFramework" />
        <Reference Include="System" />
        <Reference Include="System.Configuration" />
        <Reference Include="System.Core" />
        <Reference Include="System.Data.Entity.Design" />
        <Reference Include="System.Deployment" />
        <Reference Include="System.IO.Compression" />
        <Reference Include="System.IO.Compression.FileSystem" />
        <Reference Include="System.Windows" />
        <Reference Include="System.Xaml" />
        <Reference Include="System.Xml.Linq" />
        <Reference Include="System.Data.DataSetExtensions" />
        <Reference Include="Microsoft.CSharp" />
        <Reference Include="System.Data" />
        <Reference Include="System.Xml" />
        <Reference Include="WindowsBase" />
    </ItemGroup>
    <ItemGroup>
      <Resource Include="Windows\images\AlignHorizontalTop_16x16.png" />
      <Resource Include="Windows\images\Close_16x16.png" />
      <Resource Include="Windows\images\database.png" />
      <Resource Include="Windows\images\Home_16x16.png" />
      <Resource Include="Windows\images\key.png" />
      <Resource Include="Windows\images\New_16x16.png" />
      <Resource Include="Windows\images\Next_16x16.png" />
      <Resource Include="Windows\images\Open_16x16.png" />
      <Resource Include="Windows\images\Save_16x16.png" />
      <Resource Include="Windows\images\SelectTable_16x16.png" />
      <Resource Include="Windows\images\server.png" />
      <Resource Include="Windows\images\server_error.png" />
      <Resource Include="Windows\images\Table_16x16.png" />
    </ItemGroup>
    <ItemGroup>
      <None Update="sqlcon.cfg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="user.ini">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
