<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net48</TargetFrameworks>
        <Version>2.7.0</Version>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    </ItemGroup>
    <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
        <Reference Include="System" />
        <Reference Include="System.Core" />
        <Reference Include="System.Deployment" />
        <Reference Include="System.Net.Http" />
        <Reference Include="System.Runtime.Serialization" />
        <Reference Include="System.Xml.Linq" />
        <Reference Include="System.Data.DataSetExtensions" />
        <Reference Include="System.Data" />
        <Reference Include="System.Xml" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\syscore\syscore.csproj" />
    </ItemGroup>
</Project>