<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <RootNamespace>Sys</RootNamespace>
    <Title>syscore</Title>
    <PackageId>syscore</PackageId>
    <Version>2.7.0</Version>
  </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Tie" Version="2.0.11" />
        <PackageReference Include="syscode" Version="3.0.6" />
    </ItemGroup>
    <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
        <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
        <PackageReference Include="System.Data.OleDb" Version="9.0.7" />
        <PackageReference Include="System.CodeDom" Version="9.0.7" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
      <Reference Include="System" />
      <Reference Include="System.Core" />
      <Reference Include="System.Net.Http" />
      <Reference Include="System.Runtime.Serialization" />
      <Reference Include="System.Xml.Linq" />
      <Reference Include="System.Data.DataSetExtensions" />
      <Reference Include="System.Data" />
      <Reference Include="System.Xml" />
  </ItemGroup>
</Project>